### PR TITLE
MAINT: Update meson build according to private API changes

### PR DESCRIPTION
**Pull request by Smit-create**
* See: https://github.com/rgommers/scipy/issues/36#issuecomment-957342970

Update for the following modules are completed:

- [x] cluster
- [x] constants
- [x] fft
- [x] fftpack
- [x] integrate
- [x] interpolate
- [x] io
- [x] linalg
- [x] misc
- [x] ndimage
- [x] odr
- [x] optimize
- [x] signal
- [x] sparse
- [x]  spatial
- [x] special
- [x] stats

cc @rgommers

### CODE REVIEW

**Comment by rgommers** [comment]
Cool, looks like a good start. The separate commits like `MAINT: Update meson build files with private API ` should be easy to review; when CI turns green we should be good here.

**Comment by Smit-create** [comment]
The test failures(`scipy/sparse/linalg/_eigen/tests/test_svds.py`) are related to: https://github.com/scipy/scipy/pull/14868#issuecomment-964444731

**Comment by Smit-create** [comment]
@rgommers I see the similar failures in scipy master too. There are no failures on scipy CI because the `spare.linalg._eigen.tests` is not installed. See: https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_eigen/setup.py

**Comment by rgommers** [comment]
> There are no failures on scipy CI because the `spare.linalg._eigen.tests` is not installed. See: https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_eigen/setup.py

Ouch! That's a good catch, explains the discrepancy.

**Comment by rgommers** [comment]
So is this good to review/merge? If this `eigen/tests` thing is the only thing for getting CI green, then I think we can disable them here temporarily, until things are fixed in SciPy master.

**Comment by Smit-create** [comment]
Should I add it back in scipy?

**Comment by Smit-create** [comment]
> So is this good to review/merge?

Yes, please!

**Comment by rgommers** [comment]
> Should I add it back in scipy?

Yes, that sounds good - but only if you can get a handle on the test failures, otherwise it's a one-line change that we cannot merge because all CI turns red. See https://github.com/scipy/scipy/pull/14868#issuecomment-964444731, it may be that before that PR things all worked. If so, you can see if it's easy to remove those tests as the last comment says, and otherwise revert that whole PR.

**Comment by Smit-create** [comment]
> If this `eigen/tests` thing is the only thing for getting CI green, then I think we can disable them here temporarily, until things are fixed in SciPy master.

For this PR should we skip testing `eigen.tests` to check if CI turns green? Should I commit it with a note to remember reverting it back?

**Comment by rgommers** [comment]
> For this PR should we skip testing `eigen.tests` to check if CI turns green? Should I commit it with a note to remember reverting it back?

Yes. The easiest fix is to just not install `tests` I guess. `xfail`-ing will need to be done per tests otherwise.

**Comment by rgommers** [comment]
All macOS failures are due to: 
```
RuntimeWarning: invalid value encountered in reciprocal
```
just like before.

**Review by rgommers — COMMENTED** [review]
LGTM,M, thanks @Smit-create! Merged

**Comment by Smit-create** [comment]
>  I see the similar failures in scipy master too. There are no failures on scipy CI because the `spare.linalg._eigen.tests` is not installed. See: https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_eigen/setup.py

@rgommers, Should we open an issue in scipy so that we have a track?

**Comment by rgommers** [comment]
Yes, please do!

**Pull request merged**
