### PR TITLE
MAINT: Add larsoner

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
push-forced with an amended commit message with `ci skip` so that it shouldn't waste CIs if you decide to merge

**Review by rgommers — APPROVED** [review]
Thanks Eric.

**Comment by rgommers** [comment]
Ah wrong branch targeted, I'll manually incorporate

**Comment by larsoner** [comment]
Heh, tried to save you some work and just made more. Hopefully `git cherry-pick 2085051` is close enough!

**Comment by rgommers** [comment]
no worries, it did save me work

**Pull request merged**
