### PR TITLE
Addressing #6107

### PR DESCRIPTION
**Pull request by jlefty**
Here are the fixes for the overflow issues in the linkage function.  Let me know if there is anything else necessary (i.e. tests?)

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @jlefty! 

The extra commits you're getting because you were working off scipy master and not my branch. You could have fixed that by rebasing your branch on mine. Doesn't matter much, I cherry-picked your last commit and pushed it to https://github.com/scipy/scipy/pull/6638. 

Also changed the type defs from ``int64_t`` to ``npy_int64``. On common platforms that won't make a difference, but ``npy_int64`` should be a little more portable.

**Comment by rgommers** [comment]
You may also want to set your username to your real name (we like to include names of all contributors in the release notes). see https://docs.scipy.org/doc/numpy-dev/dev/gitwash/configure_git.html

**Comment by Josh-Lefler** [comment]
Thank you! 

I think my username is changed? I thought setting your name on your profile was enough. 

It should be @Josh-Lefler now.

**Comment by rgommers** [comment]
You don't have to change your username, ``jlefty`` is fine (and short which is handy). What you want is to associate your name with your username in the git config (that's different from your profile name), so the commit log shows that. Try ``git show`` on your commit:

    $ git show 11a0cd9
    commit 11a0cd992669319857382ca2c8f3d28ed5714e2b
    Author: jlefty <jlefty94@gmail.com>
    Date:   Thu Oct 27 15:41:34 2016 -0700

If you do 

    git config --global user.name "Josh Lefler"

then it'll show up right for commits you make after that.

**Pull request closed without merging**
