### PR TITLE
Fix many Meson build issues, mostly with Cython

### PR DESCRIPTION
**Pull request by rgommers**
Almost there, only 3 test failures left:

<details>

```
========================================================================= FAILURES ==========================================================================
___________________________________________________________________ test_odeint_full_jac ____________________________________________________________________
lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py:71: in test_odeint_full_jac
    check_odeint(JACTYPE_FULL)
lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py:52: in check_odeint
    sol, info = odeint(rhs, y0, t,
        atol       = 1e-13
        dt         = 0.125
        jacobian   = <function jac at 0x7f13e77d7790>
        jactype    = 1
        ml         = None
        mu         = None
        nsteps     = 64
        rtol       = 1e-11
        t          = array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ,
       1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 ,...6.25 , 6.375, 6.5  , 6.625,
       6.75 , 6.875, 7.   , 7.125, 7.25 , 7.375, 7.5  , 7.625, 7.75 ,
       7.875, 8.   ])
        y0         = array([1., 2., 3., 4., 5.])
lib/python3.9/site-packages/scipy/integrate/odepack.py:241: in odeint
    output = _odepack.odeint(func, y0, t, args, Dfun, col_deriv, ml, mu,
        Dfun       = <function jac at 0x7f13e77d7790>
        args       = ()
        atol       = 1e-13
        col_deriv  = 0
        dt         = array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
       0.125, 0.125, 0.125, 0.125, 0.125, 0.125,...0.125, 0.125, 0.125, 0.125, 0.125,
       0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
       0.125])
        full_output = True
        func       = <function rhs at 0x7f13e77d7820>
        h0         = 0.0
        hmax       = 0.0
        hmin       = 0.0
        ixpr       = 0
        ml         = -1
        mu         = -1
        mxhnil     = 0
        mxordn     = 12
        mxords     = 5
        mxstep     = 0
        printmessg = 0
        rtol       = 1e-11
        t          = array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ,
       1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 ,...6.25 , 6.375, 6.5  , 6.625,
       6.75 , 6.875, 7.   , 7.125, 7.25 , 7.375, 7.5  , 7.625, 7.75 ,
       7.875, 8.   ])
        tcrit      = None
        tfirst     = False
        y0         = array([1., 2., 3., 4., 5.])
lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py:10: in rhs
    banded5x5.banded5x5(t, y, dydt)
E   AttributeError: module 'scipy.integrate._test_odeint_banded' has no attribute 'banded5x5'
        dydt       = array([0., 0., 0., 0., 0.])
        t          = 0.0
        y          = array([1., 2., 3., 4., 5.])
__________________________________________________________________ test_odeint_banded_jac ___________________________________________________________________
lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py:75: in test_odeint_banded_jac
    check_odeint(JACTYPE_BANDED)
lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py:52: in check_odeint
    sol, info = odeint(rhs, y0, t,
        atol       = 1e-13
        dt         = 0.125
        jacobian   = <function bjac at 0x7f13e77d75e0>
        jactype    = 4
        ml         = 2
        mu         = 1
        nsteps     = 64
        rtol       = 1e-11
        t          = array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ,
       1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 ,...6.25 , 6.375, 6.5  , 6.625,
       6.75 , 6.875, 7.   , 7.125, 7.25 , 7.375, 7.5  , 7.625, 7.75 ,
       7.875, 8.   ])
        y0         = array([1., 2., 3., 4., 5.])
lib/python3.9/site-packages/scipy/integrate/odepack.py:241: in odeint
    output = _odepack.odeint(func, y0, t, args, Dfun, col_deriv, ml, mu,
        Dfun       = <function bjac at 0x7f13e77d75e0>
        args       = ()
        atol       = 1e-13
        col_deriv  = 0
        dt         = array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
       0.125, 0.125, 0.125, 0.125, 0.125, 0.125,...0.125, 0.125, 0.125, 0.125, 0.125,
       0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125,
       0.125])
        full_output = True
        func       = <function rhs at 0x7f13e77d7820>
        h0         = 0.0
        hmax       = 0.0
        hmin       = 0.0
        ixpr       = 0
        ml         = 2
        mu         = 1
        mxhnil     = 0
        mxordn     = 12
        mxords     = 5
        mxstep     = 0
        printmessg = 0
        rtol       = 1e-11
        t          = array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ,
       1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 ,...6.25 , 6.375, 6.5  , 6.625,
       6.75 , 6.875, 7.   , 7.125, 7.25 , 7.375, 7.5  , 7.625, 7.75 ,
       7.875, 8.   ])
        tcrit      = None
        tfirst     = False
        y0         = array([1., 2., 3., 4., 5.])
lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py:10: in rhs
    banded5x5.banded5x5(t, y, dydt)
E   AttributeError: module 'scipy.integrate._test_odeint_banded' has no attribute 'banded5x5'
        dydt       = array([0., 0., 0., 0., 0.])
        t          = 0.0
        y          = array([1., 2., 3., 4., 5.])
____________________________________________________________ test_cont_basic[500-200-ncf-arg74] _____________________________________________________________
lib/python3.9/site-packages/scipy/stats/tests/test_continuous_basic.py:189: in test_cont_basic
    check_entropy(distfn, arg, distname)
        alpha      = 0.01
        arg        = (27, 27, 0.41578441799226107)
        distfn     = <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>
        distname   = 'ncf'
        locscale_defaults = (0, 1)
        m          = array(1.09663138)
        meths      = [<bound method rv_continuous.pdf of <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>>, <bound method ...f13e6f08610>>, <bound method rv_continuous.logsf of <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>>]
        n_fit_samples = 200
        rng        = RandomState(MT19937) at 0x7F1360220A40
        rvs        = array([0.90888841, 0.87523216, 0.73228753, 1.33584017, 0.93548576,
       1.09504212, 1.15670442, 0.36786914, 0.791225...03, 1.73540023, 0.87035866, 0.73702581, 0.81477748,
       0.87362182, 1.58673099, 1.88455316, 0.61564337, 1.09912842])
        sm         = 1.0740685247899555
        sn         = 500
        spec_x     = {'levy_l': -0.5, 'pareto': 1.5, 'rv_histogram_instance': 5.0, 'tukeylambda': 0.3, ...}
        sv         = 0.1911827409537913
        v          = array(0.2013794)
        x          = 0.5
lib/python3.9/site-packages/scipy/stats/tests/common_tests.py:93: in check_entropy
    ent = distfn.entropy(*arg)
        arg        = (27, 27, 0.41578441799226107)
        distfn     = <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>
        msg        = 'ncf'
lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py:1254: in entropy
    place(output, cond0, self.vecentropy(*goodargs) + log(goodscale))
        args       = (array(27), array(27), array(0.41578442))
        cond0      = True
        goodargs   = [array([27]), array([27]), array([0.41578442])]
        goodscale  = array([1])
        kwds       = {}
        loc        = array(0)
        output     = array(0.)
        scale      = array(1)
        self       = <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>
../../../anaconda3/envs/scipy-meson/lib/python3.9/site-packages/numpy/lib/function_base.py:2163: in __call__
    return self._vectorize_call(func=func, args=vargs)
        args       = (array([27]), array([27]), array([0.41578442]))
        excluded   = set()
        func       = <bound method rv_continuous._entropy of <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>>
        kwargs     = {}
        self       = <numpy.vectorize object at 0x7f13e6eee0a0>
        vargs      = (array([27]), array([27]), array([0.41578442]))
../../../anaconda3/envs/scipy-meson/lib/python3.9/site-packages/numpy/lib/function_base.py:2246: in _vectorize_call
    outputs = ufunc(*inputs)
        args       = (array([27]), array([27]), array([0.41578442]))
        func       = <bound method rv_continuous._entropy of <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>>
        inputs     = [array([27], dtype=object), array([27], dtype=object), array([0.41578441799226107], dtype=object)]
        otypes     = 'd'
        self       = <numpy.vectorize object at 0x7f13e6eee0a0>
        ufunc      = <ufunc '_entropy (vectorized)'>
lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py:2621: in _entropy
    h = integrate.quad(integ, _a, _b)[0]
        _a         = 0.0
        _b         = inf
        args       = (27, 27, 0.41578441799226107)
        integ      = <function rv_continuous._entropy.<locals>.integ at 0x7f1365f5ff70>
        self       = <scipy.stats._continuous_distns.ncf_gen object at 0x7f13e6f08610>
lib/python3.9/site-packages/scipy/integrate/quadpack.py:400: in quad
    warnings.warn(msg, IntegrationWarning, stacklevel=2)
E   scipy.integrate.quadpack.IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
E     the requested tolerance from being achieved.  The error may be 
E     underestimated.
        a          = 0.0
        args       = ()
        b          = inf
        epsabs     = 1.49e-08
        epsrel     = 1.49e-08
        flip       = False
        full_output = 0
        func       = <function rv_continuous._entropy.<locals>.integ at 0x7f1365f5ff70>
        ier        = 2
        limit      = 50
        limlst     = 50
        maxp1      = 50
        msg        = 'The occurrence of roundoff error is detected, which prevents \n  the requested tolerance from being achieved.  The error may be \n  underestimated.'
        msgs       = {80: 'A Python error occurred possibly while calling the function.', 1: 'The maximum number of subdivisions (50) has b...\n  underestimated.', 3: 'Extremely bad integrand behavior occurs at some points of the\n  integration interval.', ...}
        points     = None
        retval     = (nan, nan, 2)
        weight     = None
        wopts      = None
        wvar       = None
================================================================== short test summary info ==================================================================
FAILED lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py::test_odeint_full_jac - AttributeError: module 'scipy.integrate._test_odeint_b...
FAILED lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py::test_odeint_banded_jac - AttributeError: module 'scipy.integrate._test_odeint...
FAILED lib/python3.9/site-packages/scipy/stats/tests/test_continuous_basic.py::test_cont_basic[500-200-ncf-arg74] - scipy.integrate.quadpack.IntegrationWa...
============================ 3 failed, 32552 passed, 2105 skipped, 11134 deselected, 107 xfailed, 8 xpassed in 340.94s (0:05:40) ============================
```

</details>

This does depend on a Meson fix that I still need to upstream: https://github.com/rgommers/meson/tree/fix-cython-mixed-sources

What is left to do:
- [ ] Upstream the fix for using generated Cython sources
- [x] Targets that depend on `cython_blas.pxd`, `cython_lapack.pxd` or `cython_special.pxd` now work, but the dependencies are not added everywhere yet - this needs fixing. The problem is that one cannot pass an object like `cython_blas_pxd` between two `subdir`'s at the same level, so probably need to move the codegen for `cython_lapack` and `cython_blas` one level up.
- [ ] `test_odeint_jac` failures are due to the `.pyf` file added in this PR, it's not correct (I'm no good at `f2py`) - see the one `WIP: BLD:` commit in this PR
- [ ] the `test_cont_basic[500-200-ncf-arg74]` failure needs checking

### CODE REVIEW

**Comment by czgdp1807** [comment]
All tests pass on my system i.e., `bash mesondev.sh ../build ~/scipy_project/meson_build/install` works fine.

**Comment by rgommers** [comment]
Okay this is green - it ran the CI from master though, not the whole test suite. Let's merge it and see if it all passes.

**Comment by rgommers** [comment]
After merging, there's four failures when running `scipy.test(parallel=2)`:
```
FAILED lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py::test_odeint_banded_jac
FAILED lib/python3.9/site-packages/scipy/integrate/tests/test_odeint_jac.py::test_odeint_full_jac
FAILED lib/python3.9/site-packages/scipy/optimize/_trustregion_constr/tests/test_report.py::test_gh12922
FAILED lib/python3.9/site-packages/scipy/stats/tests/test_continuous_basic.py::test_cont_basic[500-200-ncf-arg74]
```
Also the CI status did not turn red. I'll open 2 follow-up issues for that.

**Comment by rgommers** [comment]
Still happy though, pretty much everything is fixed:)

**Pull request merged**
