### PR TITLE
MAINT: Merge master and make private/public API changes

### PR DESCRIPTION
**Pull request by Smit-create**
cc @rgommers

### CODE REVIEW

**Comment by rgommers** [comment]
It looks like missing files are detected one by one:
```
Exception: /home/runner/work/scipy/scipy/scipy/sparse/tests/test_array_api.py is not installed
```
so you may want to run that check locally first to speed up the process.

**Comment by Smit-create** [comment]
Yeah, fixing them locally

**Comment by Smit-create** [comment]
There are many errors mostly due to `*.pyx` files, similar to:
```
ImportError while importing test module '/home/smit/Smitlunagariya/scipy/installdir/lib/python3.9/site-packages/scipy/special/tests/test_basic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/smit/anaconda3/envs/scipy-dev/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../installdir/lib/python3.9/site-packages/scipy/special/__init__.py:649: in <module>
    from . import _ufuncs
scipy/special/_ufuncs.pyx:1: in init scipy.special._ufuncs
    ???
E   ImportError: /home/smit/Smitlunagariya/scipy/installdir/lib/python3.9/site-packages/scipy/special/_ufuncs_cxx.cpython-39-x86_64-linux-gnu.so: undefined symbol: fellint_RF

```

**Comment by rgommers** [comment]
`fellint_RF` was just merged: https://github.com/scipy/scipy/pull/15135. That PR has a small change to `setup.py` which you'll want to mirror to `special/meson.build`.

**Comment by Smit-create** [comment]
> That PR has a small change to `setup.py` which you'll want to mirror to `special/meson.build`.

Yeah, I added it. I am trying to push and check if the CI passes since my ubuntu laptop had a hard disc failure(expecting to get it fixed in 2 days) and, so I'm trying from the windows laptop

**Comment by Smit-create** [comment]
Please don't mind the commits from an alternative account. I have pushed them from a different laptop.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @Smit-create!

**Comment by duetosymmetry** [comment]
macOS tests are being run with python 3.10 (see logs under 'Setup Conda Environment' and later). Not sure if this is the source of the failing tests.

**Comment by rgommers** [comment]
No that should be fine - the only failures are coming from:
```
E   RuntimeWarning: invalid value encountered in reciprocal
```
which is an issue in numpy where `np.reciprocal` gives warnings where it shouldn't (LLVM bug) and the test suite settings therefore fail the tests (pytest setting to turn warnings into errors). Apple has fixed the LLVM bug, but we're using a version where that fix hasn't shown up yet I think.

**Comment by rgommers** [comment]
Squashed the last few commits and merged this PR in commit 70ba03eab.

**Comment by Smit-create** [comment]
Thanks!!

**Pull request closed without merging**
