### PR TITLE
 CI: Add `-werror` in Meson job, and sync with upstream master

### PR DESCRIPTION
**Pull request by Smit-create**
* References: #62, #36

cc @rgommers

### CODE REVIEW

**Comment by rgommers** [comment]
The two failures on macOS are very minor, if you increase `atol` a little for those tests they will pass.

**Review by rgommers — COMMENTED** [review]
Thanks @Smit-create! The PROPACK support looks good from a quick read; I'll review in more detail after today.

**Comment by Smit-create** [comment]
> The two failures on macOS are very minor, if you increase `atol` a little for those tests they will pass.

Yes, should I change it and open a PR in scipy?

**Review by rgommers — APPROVED** [review]
This looks great, thanks @Smit-create! 

I found only one small issue: the PROPACK example files (used for testing) are not installed to the correct directories. The code looks like this:
```python
s_examples = [
  'PROPACK/single/Examples/illc1850.coord',
...
elements = [
  ['_spropack', s_src, s_examples, 'spropack.pyf'],
...
  py3.install_sources(ele[2],
      pure: false,
      subdir: 'scipy/sparse/linalg/_propack'
  )
```
The subdirs in `s_examples` are used only to identify the input files; they are installed to `subdir: 'scipy/sparse/linalg/_propack/'` and not to `subdir: 'scipy/sparse/linalg/_propack/PROPACK/single/Examples/'`. There are no test failures on this PR because the relevant file, `scipy/sparse/linalg/tests/test_propack.py `, is also not installed.

This PR is very large to read, so let's merge this as is, and address that minor issue in a follow-up. Could you do that @Smit-create?

**Comment by Smit-create** [comment]
Oops!! Missed that. I will change them in a new PR soon!

**Pull request merged**
