### PR TITLE
MAINT: Fix windows warnings

### PR DESCRIPTION
**Pull request by Smit-create**
#120

### CODE REVIEW

**Comment by Smit-create** [comment]
Windows CI is failing due to some reasons.

**Comment by rgommers** [comment]
Chocolatey failed to install Python, that looks like a flake - I've restarted to see if it happens again.

**Comment by rgommers** [comment]
Same thing:
```
  C:\ProgramData\Chocolatey\bin\choco.exe install python --version=3.9.9 --no-progress --allow-unofficial
  Chocolatey v0.12.1
  Installing the following packages:
  python
  By installing, you accept licenses for the packages.
  
  vcredist2015 v14.0.24215.20170201 [Approved]
  vcredist2015 package files install completed. Performing other installation steps.
   The install of vcredist2015 was successful.
    Software installed to 'C:\ProgramData\chocolatey\lib\vcredist2015'
  
  python3 v3.9.9 [Approved]
  python3 package files install completed. Performing other installation steps.
  Installing 64-bit python3...
  WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
  ERROR: Running ["C:\ProgramData\chocolatey\lib\python3\tools\python-3.9.9-amd64.exe" /quiet InstallAllUsers=1 PrependPath=1 TargetDir="C:\Python39" ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python3_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
  The install of python3 was NOT successful.
  Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
   See log for details.
  
  python v3.9.9 [Approved]
  python package files install completed. Performing other installation steps.
   The install of python was successful.
    Software installed to 'C:\ProgramData\chocolatey\lib\python'
  
  Chocolatey installed 2/3 packages. 1 packages failed.
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
  
  Failures
   - python3 (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
   See log for details.
  Error: The process 'C:\ProgramData\Chocolatey\bin\choco.exe' failed with exit code 1603
```

It hasn't happened on https://github.com/scipy/scipy/actions/workflows/windows.yml yet, so it may be a temporary issue.

**Comment by Smit-create** [comment]
Okay, I'll start pushing some fixes on this PR to verify Fortran warnings.

**Comment by rgommers** [comment]
Sounds good. I also updated the `main` branch of this repo to be in sync with upstream.

**Comment by Smit-create** [comment]
Github Actions results aren't visible directly here after the forced push. I'll try to open a new PR pointing at the master branch to check if Windows CI works fine or not.

**Comment by rgommers** [comment]
GitHub has some maintenance issues, but the CI jobs run fine I think: you can see them if you go to https://github.com/rgommers/scipy/actions

**Comment by Smit-create** [comment]
Yeah, I see. Without windows CI, it's difficult to figure out what exact warnings need to be fixed.

**Pull request closed without merging**
