### PR TITLE
BLD: Added interpolate to meson

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by czgdp1807** [comment]
cc @rgommers

**Comment by czgdp1807** [comment]
> /home/runner/work/scipy/scipy/scipy/interpolate/_ppoly.pyx:14:0: 'scipy/linalg/cython_lapack.pxd' not found

It seems like work is yet to be done to create this extension. I checked, `linalg/meson.build`. Found the following,

```bash
cython_blas = py3.extension_module('cython_blas',
  _generate_cy[0],  # cython_blas.pyx
  # TODO: this mixed source case isn't working yet given Meson Cython support
#  [_generate_cy[0],  # cython_blas.pyx
#   _generate_cy[2],  # cython_blas.pxd
#   _generate_cy[4],  # _blas_subroutines.h
#   'fortran_defs.h',
#  ],
  link_with : fwrappers,
  include_directories : inc_np,
  dependencies : [py3_dep, blas],
  install : true,
  subdir : 'scipy/linalg')

py3.extension_module('cython_lapack',
  _generate_cy[1],  # cython_lapack.pyx
  # TODO: this mixed source case isn't working yet given Meson Cython support
#  [_generate_cy[1],  # cython_lapack.pyx
#   _generate_cy[3],  # cython_lapack.pxd
#   _generate_cy[5],  # _lapack_subroutines.h
#   'fortran_defs.h',
#  ],
  link_with : fwrappers,
  include_directories : inc_np,
  dependencies : [py3_dep, blas],
  install : true,
  subdir : 'scipy/linalg')
```

**Comment by rgommers** [comment]
> It seems like work is yet to be done to create this extension. I checked, `linalg/meson.build`. Found the following,

It is created, but adding a dependency on it is difficult. I filed an upstream issue for it, tracked in https://github.com/rgommers/scipy/issues/31.

I suggest to add a comment to `_ppoly` that it depends on `cython_lapack.pxd` and comment out the code to build it. I think it's the very last thing to do to make everything that has the Cython linalg dependency to work; and perhaps a good hack is needed until the issue is addressed in Meson.

**Comment by czgdp1807** [comment]
The tests are passing.

**Review by rgommers — APPROVED** [review]
LGTM, just pushed a small fix for Fortran build flags. Thanks @czgdp1807!

**Pull request merged**
